# Generated by Django 5.1 on 2024-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.CharField(choices=[('option1', 'TODO'), ('option2', 'DOING'), ('option3', 'DONE')], default='TODO', max_length=100),
        ),
    ]
